### ISSUE TITLE
EACCES: permission denied, mkdir '../puppeteer/.local-chromium'

### ISSUE THREAD

**Issue by ummahusla** [albinekb/favicon-emoji#13]
```
$ sudo npm install --global favicon-emoji
Password:
/usr/local/bin/favicon-emoji -> /usr/local/lib/node_modules/favicon-emoji/cli.js

> puppeteer@0.12.0 install /usr/local/lib/node_modules/favicon-emoji/node_modules/puppeteer
> node install.js

fs.js:885
  return binding.mkdir(pathModule._makeLong(path),
                 ^

Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/favicon-emoji/node_modules/puppeteer/.local-chromium'
    at Object.fs.mkdirSync (fs.js:885:18)
    at Object.downloadRevision (/usr/local/lib/node_modules/favicon-emoji/node_modules/puppeteer/utils/ChromiumDownloader.js:99:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/favicon-emoji/node_modules/puppeteer/install.js:45:12)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@0.12.0 install: `node install.js`
npm ERR! Exit status 1
```

**Comment by albinekb** [comment]
Hi! Thanks for reporting this. I think this is a bug with the installer of puppeteer, see https://github.com/GoogleChrome/puppeteer/issues/367


I will release a version soon with updated puppeteer, that might be the trick 👍

**Comment by albinekb** [comment]
Updated and released 2.3.0, could you try that? @ummahusla 
https://github.com/albinekb/favicon-emoji/releases/tag/v2.3.0

**Comment by albinekb** [comment]
Otherwise, try to install it locally in a folder (remove --global):
`npm install favicon-emoji`
To run it from there:
`./node_modules/.bin/favicon-emoji --emoji 🤪`

I think it might be a permission issue with installing it via sudo globally.

**Comment by rpearce** [comment]
Doesn't seem to work with `yarn`, but `npm` installation is running just fine

**Comment by albinekb** [comment]
Glad you got it working, closing this one, thanks!

**Comment by hopeseekr** [comment]
After hunting around the Internet, I found a solution:

`sudo npm install -g puppeteer --unsafe-perm=true`

**Comment by BenySLO** [comment]
@hopeseekr Thanks alot, and if you have locally problems like me you can use 
`sudo npm install puppeteer --unsafe-perm=true` 
and then i had to run 
`sudo chown -R www-data node_modules/`
"www-data" is my user
