### ISSUE TITLE
Changing Emoji Library

### ISSUE THREAD

**Issue by emilbruckner** [albinekb/favicon-emoji#2]
"emoji-img" doesn't support all emojis. For example: [🗓](http://emojipedia.org/emoji/%F0%9F%97%93/). How about using [omnidan/node-emoji](https://github.com/omnidan/node-emoji ) which supports more ([from here](https://raw.githubusercontent.com/omnidan/node-emoji/master/lib/emoji.json))?

**Comment by albinekb** [comment]
Then we'll need to use something to render the text into images, maybe https://github.com/Automattic/node-canvas ?

**Comment by emilbruckner** [comment]
Never used it before, but isn't it a bit problematic that its dependencies are Cairo and Pango?

**Comment by emilbruckner** [comment]
I see two options here:

1. Saving all emojis locally, like "emoji-img" does (would take up about 7MB instead of 4MB because there are more emojis)
2. Serving the image files from a server

Which one would you go with?

**Comment by albinekb** [comment]
Yeah i think 1, so it's contained without the need for an internet connection 👌 Also no need to keep the server running

Is there pre-rendered emoji images we can get or do we need to use something like node-canvas to generate them on "prepublish"? @emilbruckner

**Comment by emilbruckner** [comment]
I would generate them "prepublish".

Going with a server still seems like a good choice to me. It could be hosted on [now.sh](https://zeit.co/now). That would also allow adding other libraries, like popular icon fonts, without having a huge package, but I guess that's not in the scope of this project?

**Comment by albinekb** [comment]
Sure we could take the server path :) then we could also serve icons like: `https://favicon-emoji.now.sh/tada.ico`

**Comment by emilbruckner** [comment]
Absolutely
I think we would have to use Docker on now.sh in order to use Cairo and Pango. 
I'll play around a bit.

**Comment by albinekb** [comment]
Cool, yeah that's the case, if youre on the zeit slack, write to me there  (@albinekb) if you need help/want to discuss things :)

**Comment by albinekb** [comment]
@emilbruckner made this https://favemoj.now.sh just for test,

rendered all emojis using the [omnidan/node-emoji](https://github.com/omnidan/node-emoji) lib, with electron, where i rendered the text in a <canvas />, and then "downloading" it via `canvas.toBlob()` 😄 

https://favemoj.now.sh/🌴

**Comment by emilbruckner** [comment]
Awesome!
I also did some tinkering and I guess it would be best for this project to just include "all" rendered emojis as img in the package?

**Comment by albinekb** [comment]
yeah, i think that's the best option here :) @emilbruckner I'll make the electron code another repo, and make it so that it's a website where you can generate them all yourself and download a .zip

**Comment by albinekb** [comment]
https://favgen.now.sh/
source: https://favgen.now.sh/_src

🎉 
i'll push that to a repo later tonight :) @emilbruckner

**Comment by emilbruckner** [comment]
@albinekb 
Great job!
Thanks for the update

**Comment by albinekb** [comment]
Code is here: https://github.com/albinekb/favicon-generator :)

What do you think of that? using that, then add images to this lib and drop the current emoji lib for images.

Then when new ones comes out you just run the generator again and drop the images in here.

**Comment by emilbruckner** [comment]
Nice
I guess that's the way to go

Thank you!

**Comment by mimischi** [comment]
Any updates on this issue?

**Comment by albinekb** [comment]
Nope @mimischi I made a script over at albinekb/favicon-generator that generates all emojis as .png's, but I'm unsure about licensing, if it's OK to add them to this repo without getting sued..

**Comment by mimischi** [comment]
I'm not fully familiar with that code, but aren't you generating the images from scratch? Maybe some internet resources can help out.

I don't think that providing this tool in an open source manner will get you sued. Consumers of the tool will probably need to inform themselves. Disclaimer: I have totally no idea of licensing and law in general :)

**Comment by albinekb** [comment]
the code over at https://github.com/albinekb/favicon-generator will generate all images from your browser, just clone the repo and run `yarn` and `yarn dev` then open http://localhost:3000, wait a minute and you'll get a .zip with all emojis as PNG  😄  

It's also hosted here: https://favgen.now.sh/

Yeah i guess :) If you want to use this lib, i can include all the images and update this lib for you tonight @mimischi

**Comment by mimischi** [comment]
I wouldn't mind for an update! I think it's a nice project :) Thanks!

**Comment by albinekb** [comment]
I'll fix it for you tonight @mimischi 👍

**Comment by albinekb** [comment]
Good news! I have rewritten the lib to use headless chrome, so now you should be able to generate any emoji! https://github.com/albinekb/favicon-emoji/pull/3

I published v2.0.1, could you try that? 🙌  @mimischi @emilbruckner

**Comment by emilbruckner** [comment]
Haven't had the time to debug anything, but I get `Cannot find module '../build/Release/sharp.node'` as error

Any idea why?

**Comment by albinekb** [comment]
What OS? @emilbruckner https://www.npmjs.com/package/sharp is used to resize the images, but I wonder why it doesn't work 🤔

**Comment by albinekb** [comment]
Ah, did you test from master? @emilbruckner then you need to run `yarn` or `npm install` and it should fix it 👍  let me know

**Comment by LinusU** [comment]
@albinekb [https://www.npmjs.com/package/resize-image-data](resize-image-data) is a pure JS solution for scaling images, not sure it would be appropriate here though and it's probably slower than sharp 😄 but at least it doesn't require a C++ compiler present to install

**Comment by albinekb** [comment]
PR welcome @LinusU 😘

**Comment by LinusU** [comment]
Got something even better coming up 😉

**Comment by LinusU** [comment]
#10

**Comment by albinekb** [comment]
Released @LinusU 🎉  @emilbruckner It should definitely work now 👌
